# compose.yaml
services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/amd64
    image: dockerml-project:latest # Optional name for the project image
    volumes:
      # Adjust container path based on WORKDIR in project Dockerfile (/app or /work)
      - ./docs:/app/_targets/user/results
      # Optional: Mount _targets cache
      # - ./_targets:/app/_targets
