suppressPackageStartupMessages({
  library("corrgram", quietly = TRUE)
  library("curl", quietly = TRUE)
  library("dplyr", quietly = TRUE)
  library("fs", quietly = TRUE)
  library("GGally", quietly = TRUE)
  library("ggplot2", quietly = TRUE)
  library("here", quietly = TRUE)
  library("janitor", quietly = TRUE)
  library("kknn", quietly = TRUE)
  library("kableExtra", quietly = TRUE)
  library("magrittr", quietly = TRUE)
  library("mice", quietly = TRUE)
  library("naniar", quietly = TRUE)
  library("psych", quietly = TRUE)
  library("purrr", quietly = TRUE)
  library("qs2", quietly = TRUE)
  library("quarto", quietly = TRUE)
  library("targets", quietly = TRUE)
  library("tarchetypes", quietly = TRUE)
  library("tibble", quietly = TRUE)
  library("tidymodels", quietly = TRUE)
  library("vroom", quietly = TRUE)
})
