name: Run Docker Pipeline and Deploy Report

on:
  push:
    branches:
      - main
      - master
  pull_request: # Good to run on PRs as well
    branches:
      - main
      - master

jobs:
  build-run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Only ONE build step now for the combined Dockerfile
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # Your single, combined Dockerfile
          platforms: linux/amd64 # As your compose.yaml specifies this
          push: false # We're not pushing to a registry, just using it in this job
          tags: dockerml-project:latest # This is the image your compose.yaml will use
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Make run_pipeline.sh executable
        run: chmod +x ./run_pipeline.sh

      - name: Run the full pipeline
        run: ./run_pipeline.sh

      - name: Check Links in Report and Markdown files
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: >
            --verbose
            --no-progress
            --accept 200,202,204,301,302,303,304,307,308
            --exclude "https://www.linkedin.com/.*"
            --exclude "https://twitter.com/.*"
            --exclude "http://localhost:.*"
            "./docs/**/*.html"  # Check all HTML files in the docs directory
            "**/*.md"           # Also check Markdown files in the repo

      - name: Deploy report to GitHub Pages
        # Run only on successful pushes to main or master
        if: success() && (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'))
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
