name: Run Docker Pipeline and Deploy Report

on:
  push:
    branches:
      - main
      - master
  pull_request: # Good to run on PRs as well
    branches:
      - main
      - master

jobs:
  build-run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check R code style
        uses: r-lib/actions/style-project
        with:
          style_rules: 'tidyverse_style'
          fail_on_change: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Only ONE build step now for the combined Dockerfile
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # Your single, combined Dockerfile
          platforms: linux/amd64 # As your compose.yaml specifies this
          push: false # We're not pushing to a registry, just using it in this job
          tags: dockerml-project:latest # This is the image your compose.yaml will use
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Make run_pipeline.sh executable
        run: chmod +x ./run_pipeline.sh

      - name: Run the full pipeline
        # Your run_pipeline.sh calls 'docker compose up --build'.
        # The '--build' flag inside it will be very fast here because
        # the 'dockerml-project:latest' image was just built and loaded
        # by the previous GitHub Actions step.
        run: ./run_pipeline.sh

      - name: Deploy report to GitHub Pages
        # Run only on successful pushes to main or master
        if: success() && (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'))
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          # Optional:
          # cname: your.custom.domain.com
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'
          # commit_message: 'Deploy report to GitHub Pages'
